survey = Survey.create(description: 'A survey for emily, the automated shuttle', name: 'Shuttle ELLI', user: User.first)

# CREATE ROLES
role = survey.roles.create(name: 'ELLI-User')

# CREATE STATIONS
station_1 = survey.stations.create(name: 'Shuttle ELLI')

# TOPICS
topic_1 = station_1.topics.create(name: 'Shuttle ELLI', description: 'Nach der Fahrt mit Shuttle ELLI')

# STATEMENTSETS + STATEMENTS + CHOICES
# AI
set = topic_1.statement_sets.create(role: role)

statement_1 = set.statements.create(style: 'single_choice', text: 'Wie oft sind Sie vor der heutigen Fahrt bereits mit ELLI gefahren?')
statement_1.choices.create(text: 'Noch nie')
statement_1.choices.create(text: 'Einmal')
statement_1.choices.create(text: 'Mehrmals')

statement_2 = set.statements.create(style: 'single_choice', text: 'Wie beurteilen Sie den Komfort der heutigen Fahrt mit ELLI?')
statement_2.choices.create(text: 'Sehr komfortabel')
statement_2.choices.create(text: 'Komfortabel')
statement_2.choices.create(text: 'Eher komfortabel')
statement_2.choices.create(text: 'Eher unkomfortabel')
statement_2.choices.create(text: 'Unkomfortabel')
statement_2.choices.create(text: 'Sehr unkomfortabel')

statement_3 = set.statements.create(style: 'single_choice', text: 'Wie sicher haben Sie sich bei der heutigen Fahrt mit ELLI gefühlt?')
statement_3.choices.create(text: 'Sehr sicher')
statement_3.choices.create(text: 'Sicher')
statement_3.choices.create(text: 'Eher sicher')
statement_3.choices.create(text: 'Eher unsicher')
statement_3.choices.create(text: 'Unsicher')
statement_3.choices.create(text: 'Sehr unsicher')

statement_4 = set.statements.create(style: 'multiple_choice', text: 'ELLI soll in Zukunft mit einem fahrerlosen Kleinbus betrieben werden. Welche Art der Überwachung würden Sie erwarten?')
statement_4.choices.create(text: 'Fernüberwachung über einen externen Kontrollraum')
statement_4.choices.create(text: 'Video-Verbindung mit Leitzentrale im Notfall')
statement_4.choices.create(text: 'Sprach-Verbindung mit Leitzentrale im Notfall')
statement_4.choices.create(text: 'Immer Überwachung durch einen Steward an Bord des Fahrzeugs')
statement_4.choices.create(text: 'Überhaupt keine menschliche Überwachung wäre für mich auch okay.')

statement_5 = set.statements.create(style: 'single_choice', text: 'Bewerten Sie die Aussage "Ich würde gern fahrerlose Kleinbusse im Alltag nutzen, wenn sie am Markt verfügbar sind."')
statement_5.choices.create(text: 'Trifft überhaupt nicht zu')
statement_5.choices.create(text: 'Trifft überwiegend nicht zu')
statement_5.choices.create(text: 'Trifft eher nicht zu')
statement_5.choices.create(text: 'Trifft eher zu')
statement_5.choices.create(text: 'Trifft überwiegend zu')
statement_5.choices.create(text: 'Trifft voll und ganz zu')

statement_6 = set.statements.create(style: 'single_choice', text: 'Bewerten Sie die Aussage "Ich würde gern einen fahrerlosen Kleinbus vom Bahnhof zu meinem Ziel nutzen (für die \'letzte Meile\')."')
statement_6.choices.create(text: 'Trifft überhaupt nicht zu')
statement_6.choices.create(text: 'Trifft überwiegend nicht zu')
statement_6.choices.create(text: 'Trifft eher nicht zu')
statement_6.choices.create(text: 'Trifft eher zu')
statement_6.choices.create(text: 'Trifft überwiegend zu')
statement_6.choices.create(text: 'Trifft voll und ganz zu')

statement_7 = set.statements.create(style: 'single_choice', text: 'Bewerten Sie die Aussage "Ich würde gern einen fahrerlosen Kleinbus von Zuhause zum Bahnhof oder der Busstation nutzen (für die \'erste Meile\')."')
statement_7.choices.create(text: 'Trifft überhaupt nicht zu')
statement_7.choices.create(text: 'Trifft überwiegend nicht zu')
statement_7.choices.create(text: 'Trifft eher nicht zu')
statement_7.choices.create(text: 'Trifft eher zu')
statement_7.choices.create(text: 'Trifft überwiegend zu')

statement_8 = set.statements.create(style: 'single_choice', text: 'Bewerten Sie die Aussage "Ich finde es gut, einen fahrerlosen Kleinbus mit weiteren unbekannten Passagieren mit dem gleichen Reiseziel zu teilen."')
statement_8.choices.create(text: 'Trifft überhaupt nicht zu')
statement_8.choices.create(text: 'Trifft überwiegend nicht zu')
statement_8.choices.create(text: 'Trifft eher nicht zu')
statement_8.choices.create(text: 'Trifft eher zu')
statement_8.choices.create(text: 'Trifft überwiegend zu')
statement_8.choices.create(text: 'Trifft voll und ganz zu')

statement_9 = set.statements.create(style: 'single_choice', text: 'Bewerten Sie die Aussage "Durch fahrerlose Kleinbusse als Zubringer werden für mich Fahrten mit dem öffentlichen Verkehr attraktiver."')
statement_9.choices.create(text: 'Trifft überhaupt nicht zu')
statement_9.choices.create(text: 'Trifft überwiegend nicht zu')
statement_9.choices.create(text: 'Trifft eher nicht zu')
statement_9.choices.create(text: 'Trifft eher zu')
statement_9.choices.create(text: 'Trifft überwiegend zu')
statement_9.choices.create(text: 'Trifft voll und ganz zu')

statement_10 = set.statements.create(style: 'single_choice', text: 'Bewerten Sie die Aussage "Autonome Shuttles sind als Zubringer zum öffentlichen Verkehr für ländliche Räume und Vororte sinnvoll."')
statement_10.choices.create(text: 'Trifft überhaupt nicht zu')
statement_10.choices.create(text: 'Trifft überwiegend nicht zu')
statement_10.choices.create(text: 'Trifft eher nicht zu')
statement_10.choices.create(text: 'Trifft eher zu')
statement_10.choices.create(text: 'Trifft überwiegend zu')
statement_10.choices.create(text: 'Trifft voll und ganz zu')

statement_11 = set.statements.create(style: 'single_choice', text: 'Bewerten Sie die Aussage "Autonome Shuttles sind als Zubringer zum öffentlichen Verkehr in der Stadt sinnvoll."')
statement_11.choices.create(text: 'Trifft überhaupt nicht zu')
statement_11.choices.create(text: 'Trifft überwiegend nicht zu')
statement_11.choices.create(text: 'Trifft eher nicht zu')
statement_11.choices.create(text: 'Trifft eher zu')
statement_11.choices.create(text: 'Trifft überwiegend zu')
statement_11.choices.create(text: 'Trifft voll und ganz zu')

statement_12 = set.statements.create(style: 'single_choice', text: 'Bewerten Sie die Aussage "Ich würde fahrerlose Kleinbusse am ehesten für Sonderfahrten nutzen (Vereinsfahrten, Möbeltransporte etc.)."')
statement_12.choices.create(text: 'Trifft überhaupt nicht zu')
statement_12.choices.create(text: 'Trifft überwiegend nicht zu')
statement_12.choices.create(text: 'Trifft eher nicht zu')
statement_12.choices.create(text: 'Trifft eher zu')
statement_12.choices.create(text: 'Trifft überwiegend zu')
statement_12.choices.create(text: 'Trifft voll und ganz zu')

statement_13 = set.statements.create(style: 'single_choice', text: 'Bewerten Sie die Aussage "Ich bevorzuge ELLI mit einem Fahrer im Vergleich zu einem autonomen Shuttle ohne Fahrer."')
statement_13.choices.create(text: 'Trifft überhaupt nicht zu')
statement_13.choices.create(text: 'Trifft überwiegend nicht zu')
statement_13.choices.create(text: 'Trifft eher nicht zu')
statement_13.choices.create(text: 'Trifft eher zu')
statement_13.choices.create(text: 'Trifft überwiegend zu')
statement_13.choices.create(text: 'Trifft voll und ganz zu')

statement_14 = set.statements.create(style: 'multiple_choice', text: 'Bewerten Sie die Aussage "Ich bevorzuge ELLI mit einem Fahrer im Vergleich zu einem autonomen Shuttle ohne Fahrer."')
statement_14.choices.create(text: 'Die Fahrt ist mit einer Monatskarte immer kostenlos.')
statement_14.choices.create(text: 'Für eine Anschlussgarantie mit der Bahn oder dem Bus würde ich auch einen Aufpreis zahlen.')
statement_14.choices.create(text: 'Für eine exklusive Gruppenbuchung (z.B. nur mit der Familie) würde ich einen Aufpreis zahlen.')
statement_14.choices.create(text: 'Für eine Nachtfahrt würde ich einen Aufpreis zahlen.')
statement_14.choices.create(text: 'Keine dieser Optionen kommt für mich in Frage.')

statement_15 = set.statements.create(style: 'single_choice', text: 'Bitte geben Sie ihr Alter an.')
statement_15.choices.create(text: 'unter 18')
statement_15.choices.create(text: '18 - 24')
statement_15.choices.create(text: '25 - 34')
statement_15.choices.create(text: '35 - 44')
statement_15.choices.create(text: '45 - 54')
statement_15.choices.create(text: '55 - 69')
statement_15.choices.create(text: 'über 69')

statement_16 = set.statements.create(style: 'single_choice', text: 'Bitte geben Sie ihr Geschlecht an.')
statement_16.choices.create(text: 'Weiblich')
statement_16.choices.create(text: 'Männlich')
statement_16.choices.create(text: 'Anderes')
