image: docker:latest
services:
- docker:dind

stages:
- build
- test
- release

variables:
  CONTAINER_IMAGE: registry.gitlab.com/innoz/innosurvey
  TEST_IMAGE: $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: $CONTAINER_IMAGE:latest
  RELEASE_IMAGE: gitlab.example.com:5555/sammy/hello_hapi:latest


before_script:
    - docker info
    - docker version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

test:
  stage: test
  script:
    - docker pull $TEST_IMAGE
    - docker run $TEST_IMAGE RAILS_ENV=test bundle exec rails db:create db:schema:load  
    # test prepare
    - docker run $TEST_IMAGE RAILS_ENV=test bundle exec rspec

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker push $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  when: on_success
  only:
    - branches
