version: '2'
services:
  innosurvey:
    build: .
    stdin_open: true
    tty: true
    command: bundle exec rails s
    volumes: 
      - .:/innosurvey
    env_file: .env
    ports: 
      - '0.0.0.0:3333:3000'
