version: '2'
services:
  innosurvey:
    build: .
    command: bundle exec rails s
    volumes: 
      - .:/innosurvey
    env_file: .env
    ports: 
      - '0.0.0.0:3000:3000'

  innosurvey_file_backup:
    image: b3vis/borgmatic
    env_file: .env
    volumes:
      - ./config/borgbackup:/config
      - ./db:/source/:ro
      - ./log:/log/
      - /backup/innoSurvey/borg_repo:/repository
      - /backup/innoSurvey/borg_cache:/cache
